giteeToken: "******"
webhookSecret: "******"
databaseType: "mysql"
databaseHost: "127.0.0.1"
databasePort: 3306
databaseName: "cibot"
databaseUserName: "root"
databasePassword: "******"
watchProjectFiles:
  - watchProjectFileOwner: openeuler
    watchprojectFileRepo: infrastructure
    watchprojectFilePath: repository/openeuler.yaml
    watchProjectFileRef: master
  - watchProjectFileOwner: openeuler
    watchprojectFileRepo: infrastructure
    watchprojectFilePath: repository/src-openeuler.yaml
    watchProjectFileRef: master
watchProjectFileDuration: 60
