---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-configmap
  namespace: bot
data:
  config.yaml: |
    giteeToken: "******"
    webhookSecret: "123456789"
    databaseType: "mysql"
    databaseHost: "127.0.0.1"
    databasePort: 3306
    databaseName: "cibot"
    databaseUserName: "root"
    databasePassword: "******"
    watchProjectFileOwner: openeuler
    watchprojectFileRepo: infrastructure
    watchprojectFilePath: repository/projects.yaml
    watchProjectFileRef: master
    watchProjectFileDuration: 60
