---
apiVersion: v1
kind: Service
metadata:
  name: botservice
  namespace: bot
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: a62480cf-d41a-435d-9a80-69f6ef312391
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 159.138.7.7
  ports:
    - name: httpport
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31200
  selector:
    app: botinfo
  type: LoadBalancer
